import imaplib

# Connect to the email server
mail = imaplib.IMAP4_SSL("imap.gmail.com")
mail.login("##########@gmail.com","app specific password generated by Google")

# Select the inbox folder
mail.select("inbox")

# Search for unread emails
status, emails = mail.search(None, 'UNSEEN')
email_ids = emails[0].split()

# Loop through the unread emails and delete them
for email_id in email_ids:
    mail.store(email_id, '+FLAGS', '\\Deleted')

# Expunge deleted emails
mail.expunge()

# Close the connection to the email server
mail.close()
mail.logout()
